/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dbms;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Moideen Aadil Shan
 */
public class HomePage extends javax.swing.JFrame {
int b=0;
    /**
     * Creates new form HomePage
     * @param a
     */
    public HomePage(int a) {
        initComponents();
        
        b=a;
        setExtendedState(HomePage.MAXIMIZED_BOTH);

    }

    private HomePage() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MatchBTN = new javax.swing.JButton();
        stadiumBTN = new javax.swing.JButton();
        teamBTN = new javax.swing.JButton();
        refereeBTN = new javax.swing.JButton();
        managerBTN = new javax.swing.JButton();
        playerBTN = new javax.swing.JButton();
        statsBTN = new javax.swing.JButton();
        contractBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 25));

        MatchBTN.setFont(new java.awt.Font("Solid Edge Stencil", 1, 18)); // NOI18N
        MatchBTN.setText("MATCHES");
        MatchBTN.setAutoscrolls(true);
        MatchBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        MatchBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MatchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatchBTNActionPerformed(evt);
            }
        });

        stadiumBTN.setFont(new java.awt.Font("Solid Edge Stencil", 1, 18)); // NOI18N
        stadiumBTN.setText("STADIUMS");
        stadiumBTN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        stadiumBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stadiumBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stadiumBTNActionPerformed(evt);
            }
        });

        teamBTN.setFont(new java.awt.Font("Solid Edge Stencil", 1, 18)); // NOI18N
        teamBTN.setText("TEAMS");
        teamBTN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        teamBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        teamBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamBTNActionPerformed(evt);
            }
        });

        refereeBTN.setFont(new java.awt.Font("Solid Edge Stencil", 1, 18)); // NOI18N
        refereeBTN.setText("REFEREES");
        refereeBTN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        refereeBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refereeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refereeBTNActionPerformed(evt);
            }
        });

        managerBTN.setFont(new java.awt.Font("Solid Edge Stencil", 1, 18)); // NOI18N
        managerBTN.setText("MANAGERS");
        managerBTN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        managerBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        managerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerBTNActionPerformed(evt);
            }
        });

        playerBTN.setFont(new java.awt.Font("Solid Edge Stencil", 1, 18)); // NOI18N
        playerBTN.setText("PLAYERS");
        playerBTN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        playerBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        playerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerBTNActionPerformed(evt);
            }
        });

        statsBTN.setFont(new java.awt.Font("Solid Edge Stencil", 1, 18)); // NOI18N
        statsBTN.setText("STATS");
        statsBTN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        statsBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsBTNActionPerformed(evt);
            }
        });

        contractBTN.setFont(new java.awt.Font("Solid Edge Stencil", 1, 18)); // NOI18N
        contractBTN.setText("CONTRACTS");
        contractBTN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        contractBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contractBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contractBTNActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("DASHBOARD");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        back.setFont(new java.awt.Font("Solid Edge Stencil", 1, 14)); // NOI18N
        back.setText("<");
        back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(statsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(291, 291, 291)
                        .addComponent(contractBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MatchBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(playerBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(300, 300, 300)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(stadiumBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(managerBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                                .addGap(269, 269, 269)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(teamBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(refereeBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(260, 260, 260)
                                .addComponent(jLabel1))))
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(331, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MatchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stadiumBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teamBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refereeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(managerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contractBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(279, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MatchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatchBTNActionPerformed
   dispose();
        
        
   
    try {
        MATCHES M = new MATCHES(b);
         M.show();
    } catch (SQLException ex) {
        Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
    }
  
        
    }//GEN-LAST:event_MatchBTNActionPerformed

    private void teamBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamBTNActionPerformed
        dispose();
        
        
    try {
         TEAMS T = new TEAMS(b);
        T.show();
    } catch (SQLException ex) {
        Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        
        
    }//GEN-LAST:event_teamBTNActionPerformed

    private void managerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerBTNActionPerformed
        dispose();
        
    try {
       MANAGERS  MA = new MANAGERS(b);
        MA.show();
    } catch (SQLException ex) {
        Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
    }
       
    }//GEN-LAST:event_managerBTNActionPerformed

    private void contractBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contractBTNActionPerformed
        dispose();
        CONTRACTS C=new CONTRACTS(b);
        C.show();
    }//GEN-LAST:event_contractBTNActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        LoginPage lp=new LoginPage();
        lp.show();
    }//GEN-LAST:event_backActionPerformed

    private void stadiumBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stadiumBTNActionPerformed
        
        STADIUMS ST=new STADIUMS(b);
        dispose();
        ST.show();
    }//GEN-LAST:event_stadiumBTNActionPerformed

    private void refereeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refereeBTNActionPerformed
        
    try {
        REFEREES rf = new REFEREES(b);
        dispose();
        rf.show();
    } catch (SQLException ex) {
        Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_refereeBTNActionPerformed

    private void playerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerBTNActionPerformed
       
    try {
        PLAYERS p = new PLAYERS(b);
        dispose();
        p.show();
    } catch (SQLException ex) {
        Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
    }
       
       
       
    }//GEN-LAST:event_playerBTNActionPerformed

    private void statsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsBTNActionPerformed
        dispose();
    try {
        STATS s = new STATS(b);
        s.show();
    } catch (SQLException ex) {
        Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_statsBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MatchBTN;
    private javax.swing.JButton back;
    private javax.swing.JButton contractBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton managerBTN;
    private javax.swing.JButton playerBTN;
    private javax.swing.JButton refereeBTN;
    private javax.swing.JButton stadiumBTN;
    private javax.swing.JButton statsBTN;
    private javax.swing.JButton teamBTN;
    // End of variables declaration//GEN-END:variables
}
